/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.iulia.gardener.api

import com.iulia.gardener.model.PlantTypeDto
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMethod
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.PathVariable
import kotlin.collections.List

@Validated
@RequestMapping("/api")
interface PlantsApi {


    @RequestMapping(
            value = ["/plants"],
            produces = ["application/json"],
            method = [RequestMethod.GET])
    fun getPlants(): ResponseEntity<List<PlantTypeDto>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @RequestMapping(
            value = ["/plants/{id}"],
            produces = ["application/json"],
            method = [RequestMethod.GET])
    fun getPlant( @PathVariable("id") id: java.util.UUID
    ): ResponseEntity<PlantTypeDto> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }


    @RequestMapping(
            value = ["/plants"],
            produces = ["application/json"],
            consumes = ["application/json"],
            method = [RequestMethod.POST])
    fun postPlant(@RequestBody plantTypeDto: PlantTypeDto
): ResponseEntity<PlantTypeDto> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
