package com.iulia.gardener.model


/**
* 
* Values: SIMPLE,WITH_LEAFLETS,PINNATE_COMPOUND,PALMATE_COMPOUND,DOUBLE_COMPOUND
*/
enum class LeafDivisionOfBlade(val value: kotlin.String) {

    SIMPLE("SIMPLE"),

    WITH_LEAFLETS("WITH_LEAFLETS"),

    PINNATE_COMPOUND("PINNATE_COMPOUND"),

    PALMATE_COMPOUND("PALMATE_COMPOUND"),

    DOUBLE_COMPOUND("DOUBLE_COMPOUND");

}

